import typing
from .terminal import Cursor


__version__: str


class Cell:
    def __init__(self) -> None: ...
    def is_default(self) -> bool: ...
    @property
    def char(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def pen(self) -> Pen: ...
    def set(self, ch: str, width: int, pen: Pen) -> None: ...


class Charset:
    Ascii: typing.Final[Charset]
    Drawing: typing.Final[Charset]
    
    def translate(self, ch: str) -> str: ...


class Color:
    class RGB(Color):
        def __init__(self, r: int, g: int, b: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0, 1, 2]) -> int: ...
    
    class Indexed(Color):
        def __init__(self, index: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...


class Line:
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    @property
    def cells(self) -> list[Cell]: ...
    def __getitem__(self, index: int) -> Cell: ...
    def chunks(self, predicate: typing.Callable[[Cell, Cell], bool]) -> list[list[Cell]]: ...
    @property
    def text(self) -> str: ...


class Pen:
    def __init__(self) -> None: ...
    def is_default(self) -> bool: ...
    @property
    def foreground(self) -> Color | None: ...
    @property
    def background(self) -> Color | None: ...
    @property
    def bold(self) -> bool: ...
    @bold.setter
    def bold(self, value: bool) -> None: ...
    @property
    def faint(self) -> bool: ...
    @faint.setter
    def faint(self, value: bool) -> None: ...
    @property
    def italic(self) -> bool: ...
    @italic.setter
    def italic(self, value: bool) -> None: ...
    @property
    def underline(self) -> bool: ...
    @underline.setter
    def underline(self, value: bool) -> None: ...
    @property
    def strikethrough(self) -> bool: ...
    @strikethrough.setter
    def strikethrough(self, value: bool) -> None: ...
    @property
    def blink(self) -> bool: ...
    @blink.setter
    def blink(self, value: bool) -> None: ...
    @property
    def inverse(self) -> bool: ...
    @inverse.setter
    def inverse(self, value: bool) -> None: ...


class Vt:
    def __init__(self, cols: int, rows: int, scrollback_limit: int | None = None) -> None: ...
    def feed_str(self, s: str) -> tuple[list[int], list[Line]]: ...
    def feed(self, ch: str) -> None: ...
    @property
    def size(self) -> tuple[int, int]: ...
    def resize(self, cols: int, rows: int) -> tuple[list[int], list[Line]]: ...
    def view(self) -> list[Line]: ...
    def lines(self) -> list[Line]: ...
    def __getitem__(self, index: int) -> Line: ...
    def text(self) -> list[str]: ...
    @property
    def cursor(self) -> Cursor: ...
    @property
    def cursor_key_app_mode(self) -> bool: ...
    def dump(self) -> str: ...

