import typing
from . import Charset, Color


class Parser:
    def __init__(self) -> None: ...
    def feed(self, input: str) -> Function | None: ...


class State:
    Ground: typing.Final[State]
    Escape: typing.Final[State]
    EscapeIntermediate: typing.Final[State]
    CsiEntry: typing.Final[State]
    CsiParam: typing.Final[State]
    CsiIntermediate: typing.Final[State]
    CsiIgnore: typing.Final[State]
    DcsEntry: typing.Final[State]
    DcsParam: typing.Final[State]
    DcsIntermediate: typing.Final[State]
    DcsPassthrough: typing.Final[State]
    DcsIgnore: typing.Final[State]
    OscString: typing.Final[State]
    SosPmApcString: typing.Final[State]


class Function:
    class Bs(Function):
        def __init__(self) -> None: ...
    
    class Cbt(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cha(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cht(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cnl(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cpl(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cr(Function):
        def __init__(self) -> None: ...
    
    class Ctc(Function):
        def __init__(self, arg: CtcOp) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> CtcOp: ...
    
    class Cub(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cud(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cuf(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Cup(Function):
        def __init__(self, arg1: int, arg2: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0, 1]) -> int: ...
    
    class Cuu(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Dch(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Decaln(Function):
        def __init__(self) -> None: ...
    
    class Decrc(Function):
        def __init__(self) -> None: ...
    
    class Decrst(Function):
        def __init__(self, arg: list[DecMode]) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> list[DecMode]: ...
    
    class Decsc(Function):
        def __init__(self) -> None: ...
    
    class Decset(Function):
        def __init__(self, arg: list[DecMode]) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> list[DecMode]: ...
    
    class Decstbm(Function):
        def __init__(self, arg1: int, arg2: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0, 1]) -> int: ...
    
    class Decstr(Function):
        def __init__(self) -> None: ...
    
    class Dl(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Ech(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Ed(Function):
        def __init__(self, arg: EdScope) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> EdScope: ...
    
    class El(Function):
        def __init__(self, arg: ElScope) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> ElScope: ...
    
    class G1d4(Function):
        def __init__(self, arg: Charset) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> Charset: ...
    
    class Gzd4(Function):
        def __init__(self, arg: Charset) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> Charset: ...
    
    class Ht(Function):
        def __init__(self) -> None: ...
    
    class Hts(Function):
        def __init__(self) -> None: ...
    
    class Ich(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Il(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Lf(Function):
        def __init__(self) -> None: ...
    
    class Nel(Function):
        def __init__(self) -> None: ...
    
    class Print(Function):
        def __init__(self, arg: str) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> str: ...
    
    class Rep(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Ri(Function):
        def __init__(self) -> None: ...
    
    class Ris(Function):
        def __init__(self) -> None: ...
    
    class Rm(Function):
        def __init__(self, arg: list[AnsiMode]) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> list[AnsiMode]: ...
    
    class Scorc(Function):
        def __init__(self) -> None: ...
    
    class Scosc(Function):
        def __init__(self) -> None: ...
    
    class Sd(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Sgr(Function):
        def __init__(self, arg: list[SgrOp]) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> list[SgrOp]: ...
    
    class Si(Function):
        def __init__(self) -> None: ...
    
    class Sm(Function):
        def __init__(self, arg: list[AnsiMode]) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> list[AnsiMode]: ...
    
    class So(Function):
        def __init__(self) -> None: ...
    
    class Su(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Tbc(Function):
        def __init__(self, arg: TbcScope) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> TbcScope: ...
    
    class Vpa(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Vpr(Function):
        def __init__(self, arg: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> int: ...
    
    class Xtwinops(Function):
        def __init__(self, arg: XtwinopsOp) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> XtwinopsOp: ...


class AnsiMode:
    Insert: typing.Final[AnsiMode]
    NewLine: typing.Final[AnsiMode]


class CtcOp:
    Set: typing.Final[CtcOp]
    ClearCurrentColumn: typing.Final[CtcOp]
    ClearAll: typing.Final[CtcOp]


class DecMode:
    CursorKeys: typing.Final[DecMode]
    Origin: typing.Final[DecMode]
    AutoWrap: typing.Final[DecMode]
    TextCursorEnable: typing.Final[DecMode]
    AltScreenBuffer: typing.Final[DecMode]
    SaveCursor: typing.Final[DecMode]
    SaveCursorAltScreenBuffer: typing.Final[DecMode]


class EdScope:
    Below: typing.Final[EdScope]
    Above: typing.Final[EdScope]
    All: typing.Final[EdScope]
    SavedLines: typing.Final[EdScope]


class ElScope:
    ToRight: typing.Final[ElScope]
    ToLeft: typing.Final[ElScope]
    All: typing.Final[ElScope]


class SgrOp:
    class Reset(SgrOp):
        def __init__(self) -> None: ...
    
    class SetBoldIntensity(SgrOp):
        def __init__(self) -> None: ...
    
    class SetFaintIntensity(SgrOp):
        def __init__(self) -> None: ...
    
    class SetItalic(SgrOp):
        def __init__(self) -> None: ...
    
    class SetUnderline(SgrOp):
        def __init__(self) -> None: ...
    
    class SetBlink(SgrOp):
        def __init__(self) -> None: ...
    
    class SetInverse(SgrOp):
        def __init__(self) -> None: ...
    
    class SetStrikethrough(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetIntensity(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetItalic(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetUnderline(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetBlink(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetInverse(SgrOp):
        def __init__(self) -> None: ...
    
    class ResetStrikethrough(SgrOp):
        def __init__(self) -> None: ...
    
    class SetForegroundColor(SgrOp):
        def __init__(self, arg: Color) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> Color: ...
    
    class ResetForegroundColor(SgrOp):
        def __init__(self) -> None: ...
    
    class SetBackgroundColor(SgrOp):
        def __init__(self, arg: Color) -> None: ...
        def __getitem__(self, index: typing.Literal[0]) -> Color: ...
    
    class ResetBackgroundColor(SgrOp):
        def __init__(self) -> None: ...


class TbcScope:
    CurrentColumn: typing.Final[TbcScope]
    All: typing.Final[TbcScope]


class XtwinopsOp:
    class Reset(XtwinopsOp):
        def __init__(self, arg1: int, arg2: int) -> None: ...
        def __getitem__(self, index: typing.Literal[0, 1]) -> int: ...

