import typing
from . import Line
from .parser import Function


class Cursor:
    def __init__(self, row: int, col: int, visible: bool = True) -> None: ...
    @property
    def row(self) -> int: ...
    @property
    def col(self) -> int: ...
    @property
    def visible(self) -> bool: ...


class Terminal:
    def __init__(self, size: tuple[int, int] = (80, 24), scrollback_limit: int | None = None) -> None: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def active_buffer_type(self) -> BufferType: ...
    def execute(self, fun: Function) -> None: ...
    @property
    def cursor(self) -> Cursor: ...
    def gc(self) -> list[Line]: ...
    def changes(self) -> list[Line]: ...
    def resize(self, cols: int, rows: int) -> bool: ...
    def view(self) -> list[Line]: ...
    def lines(self) -> list[Line]: ...
    def __getitem__(self, index: int) -> Line: ...
    def text(self) -> list[str]: ...
    @property
    def cursor_keys_app_mode(self) -> bool: ...
    def dump(self) -> str: ...


class BufferType:
    Primary: typing.Final[BufferType]
    Alternate: typing.Final[BufferType]

