import typing
from . import Line, Vt


class TextUnwrapper:
    def __init__(self) -> None: ...
    def push(self, line: Line) -> str | None: ...
    def flush(self) -> str | None: ...


class TextCollector:
    def __init__(self, vt: Vt) -> None: ...
    def feed_str(self, s: str) -> list[str]: ...
    def resize(self, cols: int, rows: int) -> list[str]: ...
    def flush(self) -> list[str]: ...

